version: "3"
services:
  mysql_db:
    image: ensinatech/mysql
    hostname: db
    networks:
      - phpinfo
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 256M
      restart_policy:
        condition: on-failure
    volumes:
      - ~/ensinatech/php1/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: minhasenha
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    networks:
      - phpinfo
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 256M
      restart_policy:
        condition: on-failure
    depends_on:
      - mysql_db
    ports:
      - 8081:80

  phpinfo:
    image: ensinatech/phpinfo:v2
    networks:
      - phpinfo
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.1"
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 256M
      restart_policy:
        condition: on-failure
    depends_on:
      - mysql_db
    ports:
      - 8080:80
networks:
  phpinfo:
